import {Profesional} from "@/profesionales/ClaseProfesionales";

export const doctores = [
    new Profesional(
        "daniel",
        "lin",
        "23162",
        "cardiologia",
        ["lunes", "miercoles", "jueves"],
        [
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"],
            ["14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"],
            ["14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"]
        ],
        obrasSocialesQueAtiende
    ),
    new Profesional(
        "guadalupe",
        "baez",
        "24582",
        "cardiologia",
        ["lunes", "martes", "miercoles"],
        [
            ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30"],
            ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30"],
            ["10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30"]
        ],
        obrasSocialesQueAtiende
    ),
    new Profesional(
        "patricio",
        "heredia",
        "34913",
        "cardiologia",
        ["martes", "viernes"],
        [
            ["14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30"],
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30"],
        ],
        obrasSocialesQueAtiende
    ),

    new Profesional("berta",
        "suhr",
        "63058",
        "dermatologia",
        ["lunes", "martes", "miercoles", "jueves", "viernes"],
        [
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"],
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"],
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"],
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"],
            ["8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30"]
        ],
        obrasSocialesQueAtiende),
    new Profesional("rafael",
        "rios",
        "50543",
        "dermatologia",
        ["martes", "miercoles", "sabado"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("marco",
        "esposito",
        "46875",
        "endocrinologia",
        diasQueAtiende,
        ["lunes", "miercoles"],
        obrasSocialesQueAtiende),

    new Profesional("federico",
        "acevedo",
        "43039",
        "gastroenterologia",
        ["lunes", "martes", "miercoles", "jueves", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
    new Profesional("amparo",
        "guzman",
        "71305",
        "gastroenterologia",
        ["miercoles", "jueves", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("mirian",
        "ruso",
        "50826",
        "ginecologia",
        ["martes", "miercoles", "jueves"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("martina",
        "brizuela",
        "84254",
        "hematologia",
        ["martes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("jose luis",
        "carpio",
        "90839",
        "hepatologia",
        ["lunes", "jueves"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("omar",
        "segarra",
        "21954",
        "nefrologia",
        ["mertes", "miercoles"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("lucía",
        "wendler",
        "54483",
        "neonatologia",
        ["lunes", "miercoles", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
    new Profesional("hector",
        "baudino",
        "66646",
        "neonatologia",
        ["martes", "jueves", "sabado"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("lucio",
        "chavez",
        "58183",
        "neumonologia",
        ["jueves"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("victor",
        "mesa",
        "48973",
        "neurologia",
        ["jueves", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("oscar",
        "mezar",
        "59866",
        "nutriologia",
        ["miercoles"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("emilia",
        "ovejero",
        "47754",
        "obstetricia",
        ["lunes", "jueves", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("jeremias",
        "davalle",
        "26474",
        "oncologia",
        ["lunes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("tomas",
        "taborda",
        "56575",
        "pediatria",
        ["lunes", "martes", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
    new Profesional("carolina",
        "brasel",
        "87061",
        "pediatria",
        ["miercoles", "jueves"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("mario",
        "azuaga",
        "17193",
        "psiquiatria",
        ["lunes", "miercoles"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("alejandra",
        "pascualetti",
        "27749",
        "reumatologia",
        ["lunes", "martes", "miercoles", "jueves"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("sandra",
        "llano",
        "78065",
        "toxicologia",
        ["jueves", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("claudia",
        "reyes",
        "78065",
        "traumatologia",
        ["martes", "miercoles"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
    new Profesional("pablo",
        "malisan",
        "63667",
        "traumatologia",
        ["lunes", "martes", "viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
    new Profesional("rodrigo",
        "lescano",
        "70473",
        "traumatologia",
        ["jueves", "viernes", "sabado"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),

    new Profesional("jose",
        "dono",
        "81485",
        "urologia",
        ["viernes"],
        horariosQueAtiende,
        obrasSocialesQueAtiende),
]
